### ISSUE TITLE
Issue with Dataset Directory

### ISSUE THREAD

**Issue by znbmalik** [gulvarol/ltc#10]
Hi, I am trying to run your model to understand it in more detail. but I am facing issue with Dataset Directory. I have generated train/test splits by executing matlab script (splits.m). Now I want to execute preprocess_flow.lua and preprocess_rgb.lua scripts but base directory mentioned in these scripts are not there in datasets folder. Please guide me how can I get '/home/gvarol/datasets/UCF101/flow/jpg/' and '/home/gvarol/datasets/UCF101/rgb/jpg/'?

**Comment by gulvarol** [comment]
Hi, `rgb/jpg/` folders must be simple frame extraction (e.g., with ffmpeg), and `flow/jpg/` were the result of the flow extraction as linked from the readme. However, I would encourage you to use more up to date repositories to train on ucf101, which is now already part of the built-in `torchvision.datasets`.

**Comment by znbmalik** [comment]
Thank You for the response. I will proceed accordingly.
